### ISSUE TITLE
Redaxo im Unterverzeichnis

### ISSUE THREAD

**Issue by zephir-wb** [Sioweb/redaxo_assets#14]
Wenn Redaxo in einem Unterverzeichnis installiert ist, funktioniert Assets nicht.
Schön wäre z.B. eine Einstellung in den Settings, in der man angeben kann, ob die generierte Datei über eine komplette Url eingebunden wird.

**Comment by Sioweb** [comment]
Danke, ich fixe das so bald wie möglich!

**Comment by zephir-wb** [comment]
Hier ein dirty Workarround:

    
    <link rel="stylesheet" href="assets/addons/assets/fe/standard.min.css">

nicht hübsch, aber funktioniert.

**Comment by Sioweb** [comment]
Ho! Danke

In 2.8.1 sollte das behoben sein.
