### ISSUE TITLE
Wenn Eigenschaft gelöscht wird, wird die min Datei nicht aktualisiert

### ISSUE THREAD

**Issue by dtpop** [Sioweb/redaxo_assets#15]
Wenn ich beispielsweise eine Eigenschaft in einer Less Datei lösche

Vorher:

.meineklasse {
    left: 200px;
}

nachher:

[nichts]

oder:

.meineklasse {
}

so wird die minifizierte Datei nicht aktualisiert, die alten Eigenschaften bleiben bestehen. Cache löschen hilft auch nicht. Manuelles löschen hilft.

**Comment by Sioweb** [comment]
Ho!

Sind das Frontend- oder Backend-Dateien?

**Comment by dtpop** [comment]
Hallo Sascha,
es sind FE-Dateien. Aber so 100%ig nachvollziehbar ist es nicht. Ich 
habe jetzt eine Datei da funktioniert es.
Du kannst das Issue erstmal schließen. Ich werde das Phänomen mal weiter 
beobachten und wenn ich Zeit habe genauere Infos dazu schreiben.
Merci und viele Grüße!

Am 04.02.16 um 14:39 schrieb Sascha Weidner:

**Comment by Sioweb** [comment]
Super danke!
