### ISSUE TITLE
Fehler in der URL-Umschreibung

### ISSUE THREAD

**Issue by webghostx** [Sioweb/redaxo_assets#17]
Ich vermute einen Fehler im Bereich von https://github.com/Sioweb/redaxo_assets/blob/master/lib/Assets.php#L163 bzw. den nachfolgenden replaces.

Wenn ich font-awesome in meiner .less einbinde `@import "../css/font-awesome.css";`
dann kommt sowas raus:

` */@font-face{font-family:'FontAwesome';src:url("../../../../assets/default/less//var/www/rex5base.dev/public/assets/default/fonts/fontawesome-webfont.eot?v=4.5.0");src:url("../../../../assets/default/less//var/www/rex5base.dev/public/assets/default/fonts/fontawesome-webfont.eot?#iefix&v=4.5.0") format('embedded-opentype'), url('/var/www/rex5base.dev/public/assets/default/fonts/fontawesome-webfont.woff2?v=4.5.0') format('woff2'), url('/var/www/rex5base.dev/public/assets/default/fonts/fontawesome-webfont.woff?v=4.5.0') format('woff'), url('/var/www/rex5base.dev/public/assets/default/fonts/fontawesome-webfont.ttf?v=4.5.0') format('truetype'), url('/var/www/rex5base.dev/public/assets/default/fonts/fontawesome-webfont.svg?v=4.5.0#fontawesomeregular')`

**Comment by webghostx** [comment]
ich habe nun die font-awesome.css übers Backend eingebunden.  Allerdings kommt die Umschreibung https://github.com/Sioweb/redaxo_assets/blob/master/lib/Assets.php#L165 nicht mit folgendem Block klar:

```
@font-face {
   font-family: 'FontAwesome';
   src: url('../fonts/fontawesome-webfont.eot?v=4.5.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.5.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.5.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.5.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.5.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.5.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

**ohne Doppelpunkt**  im regex
```
$Parser['data'] = preg_replace("|:([^url]*\s*)url[^(]*\([\"']*([^)\"\']*)[\"']*\)|is",':$1url("../../../../'.ltrim($path,'/').'/$2")',$Parser['data']);
```
scheint es zu funktionieren

**Comment by Sioweb** [comment]
Ho! Danke,

ich habe eben noch eine verbesserte Version hochgeladen. Nach einem Update sollte es funktionieren, nach dem ein Asset aktualisiert wurde.
