### ISSUE TITLE
Sets: Frontend Ausgabe: Kommentare ein / ausschalten

### ISSUE THREAD

**Issue by olien** [Sioweb/redaxo_assets#7]
evtl. bei den Sets Einstellungen eine Checkbox einbauen um bei den generierten Files die Kommentare auszublenden

**Comment by Sioweb** [comment]
Ja, ich denke dass ich pro Datei ein weitere Einstellungen brauche, ich weiß nur noch nicht wie ich die darstellen soll. Ich denke dass ich neben die Checkbox noch ein Icon mache, was ein kleines Layer mit weiteren Einstellungen öffnet "SourceMap? StrictMath? Compress? Comments?"

**Comment by olien** [comment]
evtl. das "Label" _Datei_ nach links. .. rechts die Checkboxen und unter den Checkboxen den Dateipfad/Namen?

**Comment by Sioweb** [comment]
Sollte jetzt gehen.
