### ISSUE TITLE
@import sass

### ISSUE THREAD

**Issue by olien** [Sioweb/redaxo_assets#8]
Hallo,

kann ich in einer Datei die ich in einem Set definiert habe kein @import benutzen?
Bekomme einen 404er. 

LG
Oliver

**Comment by Sioweb** [comment]
Oh vermutlich ist der Pfad in der master datei falsch, da die ja wo anderst abgespeichert wird.

**Comment by olien** [comment]
Die Master und die zu inkludene Datei liegen im gleichen Ordner. da mache ich den @import ohne Pfadangabe.

**Comment by Sioweb** [comment]
Die Master-Datei wird von dem Addon erzeugt und liegt unter /assets/addons/assets/fe/ :)

**Comment by olien** [comment]
Ähm.. :-)

**Comment by olien** [comment]
Sag mal kannst du fürs Frostend nicht einfach die Dateien dort kompilieren wo die liegen?

**Comment by Sioweb** [comment]
Ja das hab ich noch vor. Ich denke dass ich dass nächste Woche einbauen kann.

**Comment by olien** [comment]
Muss dafür irgendwo nur eine Pfadangabe geändert werden und ich kann mir das angucken oder ist das "was wildes"?

**Comment by Sioweb** [comment]
Das ist was wildes. Du kannst generell den Pfad relativ zum Master-Verzeichnis machen, aber da ich das Feature eh bald einbaue wäre das Zeitverschwendung.

**Comment by olien** [comment]
ok. danke

**Comment by Sioweb** [comment]
Problem behoben in https://github.com/factorylabs/redaxo_assets/commit/41b3b194955d5ed64bb49835dd9bd23086d21a72

**Comment by olien** [comment]
Die Pfade stimmen jetzt. Danke.

In der erzeugten .css Datei wird aber auch der Import geschrieben und die Dateien nicht wirklich includiert z.B.: 

@import 'vars';
@import 'module/trenner';

Damit kann css nichts anfangen....

**Comment by Sioweb** [comment]
Was ist wars und was ist module/trenner? Wo kommen die Werte her?

**Comment by olien** [comment]
Die sind von mir.... kannst Du eigentlich ignorieren.
Ich wollte sagen:

wenn ich in der scss Datei etwas mit @imort importieren möchte wird in der generierten css Datei auch @import geschrieben. Dort sollte ja dann der css Code der importierten Datei enthalten sein.

**Comment by Sioweb** [comment]
Also vars.sass oder so, soll direkt eingebunden werden?

**Comment by olien** [comment]
ja. z.B.:

@import 'module/trenner';

ist die Datei _trenner.scss im Ordner module

**Comment by Sioweb** [comment]
Hm okay, dass bau ich demnächst mal als feature ein. Sobald ich wieder etwas Zeit hab. Du kannst ja die CSS Dateien mit in das Set packen, dann werden die ja auch eingebunden.

**Comment by olien** [comment]
ok. danke

**Comment by olien** [comment]
Hi,

guckt Ihr euch zufällig das Problem mit dem  "_"  in der nächsten Zeit noch an?

http://www.redaxo.org/de/forum/addons-packages-f43/assets-addon-scss-und-import-t20901.html?hilit=assets#p117367

LG
Oliver

**Comment by olien** [comment]
Wenn es denn irgendwann läuft (keine Eile) würde ich mich über ein Beispiel freuen wie z.B. die SASS Version von Bootstrab eingebunden wird:

https://github.com/twbs/bootstrap-sass

LG
Oliver
